2019-10-18 15:50:13,987 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:19:46,772 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:20:26,967 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:21:04,839 ERROR: Exception on /index [POST] [in /home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/climb/quickgig/app/routes.py", line 22, in index
    gig = Gig(detail=form.gig.data, employer=current_user)
  File "<string>", line 4, in __init__
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 840, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'detail' is an invalid keyword argument for Gig
2019-10-18 16:24:02,293 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:24:47,427 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:28:23,272 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:37:27,362 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:38:04,168 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:39:23,129 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:39:55,364 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 16:45:55,413 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 17:03:45,067 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 17:04:50,676 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 17:07:36,067 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 17:08:24,595 ERROR: Exception on /user/dnilasor [GET] [in /home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/climb/quickgig/app/routes.py", line 75, in user
    return render_template('user.html', user=user, gigs=gigs)
NameError: name 'gigs' is not defined
2019-10-18 17:10:15,696 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-18 17:10:23,825 ERROR: Exception on /user/dnilasor [GET] [in /home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/climb/quickgig/app/routes.py", line 75, in user
    return render_template('user.html', user=user, gigs=gigs)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/climb/quickgig/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/climb/quickgig/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/climb/quickgig/app/templates/user.html", line 19, in block "content"
    {% include '_gig.html' %}
  File "/home/climb/quickgig/app/templates/_gig.html", line 3, in top-level template code
    <td><img src="{{ gig.author.avatar(36) }}"></td>
  File "/home/climb/quickgig/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
2019-10-18 17:11:16,619 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-19 07:31:06,132 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 11:10:36,988 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 11:12:24,723 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 11:38:11,202 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 12:19:32,435 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 12:24:15,052 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 12:24:45,563 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 12:27:23,545 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 12:27:30,530 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 12:27:32,563 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:00:12,373 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:02:06,007 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:03:02,222 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:03:50,033 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:04:14,374 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:33:38,439 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:36:25,315 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:37:44,016 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:38:03,006 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:39:07,021 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:39:34,951 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:42:03,955 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:45:07,221 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
2019-10-22 13:45:37,618 INFO: Quickgig startup [in /home/climb/quickgig/app/__init__.py:37]
